on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements-dev.txt; fi
        - name: Render Deploy Action
    - name: Render Deploy Action
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: 
          srv-csfoi40gph6c73f6so00
        api-key: 
          rnd_yFLlGCd5mA7tjVdoDf0E29K8paJW
    - name: EC2 salaH
      run: |
            echo "${{secrets.AWS_EC2_PEM}}" >private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-3-220-28-2.compute-1.amazonaws.com "
            cd POC/;git pull;./iniciarApp.sh;"
